### ISSUE TITLE
Shooter Motor Not Working

### ISSUE THREAD

**Issue by mzakocs** [Pridetronics/InfiniteRechargeV3#10]
Checked through the shooter code blame and history and nothing has changed since Friday except for changing the button ID from 1 to 4.
On Friday, we tested it on Euans computer without using any sort of breakout USB box, the controllers were hooked up directly to his USB ports.
Here's what we should do to try and fix the issue:
1. Make sure the shooter motor controller is hooked up to the right port on the RoboRIO
2. Make sure the two controllers are actually functioning properly, we can check this in driverstation
3. Try the controllers plugged directly into the USB ports and possibly recreate conditions w Euans computer on Friday
4. If all of this fails, we can try and test the shooter motor by just running it as soon as the robot turns on or through the CANSparkMax software to make sure the controller and motor are working properly
I know that we don't want to have to use Euans laptop every time we want to use the shooter, but actually getting the motor to work again would make us not look like clowns in front of the harsh Charlie and Wendell and also help us figure out what's going on.
Thanks guys.

**Comment by tcjinaz** [comment]
Comments below
On 3/3/20 7:35 PM, Mitchell Zakocs wrote:
> Checked through the shooter code blame and history and nothing has changed since Friday except for changing the button ID from 1 to 4.
> On Friday, we tested it on Euans computer without using any sort of breakout USB box, the controllers were hooked up directly to his USB ports.
> Here's what we should do to try and fix the issue:
> 1. Make sure the shooter motor controller is hooked up to the right port on the RoboRIO
Motors are not on ports on the RoboRIO, they are all on the CAN (Controller Area Network) Bus, each with a unique ID. These ID's are defined in The Contract, configured into the motor controllers (Phoenix Tuner; Lucky?), and are also defined in Constants.java for use in the program (RobotContainer.java). Constants.java and RobotContainer.java changed on Monday. Were the CAN ID's cross-checked between the H/W and S/W?
>
> 2. Make sure the two controllers are actually functioning properly, we can check this in driverstation

Never mind functioning properly, test to answer the questions "is this the driver's joystick?" and "is this the shooter joystick?" Revise in the driver station as required. Do not just swap USB ports. This must be part of the driver setup checklist.

We need to use USB port multipliers to reduce the wear and tear on the computers.
>
> 3. Try the controllers plugged directly into the USB ports and possibly recreate conditions w Euans computer on Friday

Nope. See (2).

We keep ignoring this: use SmartDashboard calls, LiveWindow calls and Test Mode to instrument the code and see what the robot is up to when it is not behaving as imagined, and for hardware testing.

What's different on Euan's computer?

.

.

.

Time's up. The intermediate files created in the build process in the workspace he is using. If he were to check out the same branch that is trouble elsewhere into a new workspace, that project would have the same problems.

Some of the problem seems to be that the merge between the "mitch" and "EuanB" branches did not result in what you wanted.
>
> 4. If all of this fails, we can try and test the shooter motor by just running it as soon as the robot turns on or through the CANSparkMax software to make sure the controller and motor are working properly
See (3).
>
> I know that we don't want to have to use Euans laptop every time we want to use the shooter, but actually getting the motor to work again would make us not look like clowns in front of the harsh Charlie and Wendell and also help
Too Late
>  us figure out what's going on.
> Thanks guys.
>
See ya in Flag,

Tim

**Comment by mzakocs** [comment]
> Comments below
> On 3/3/20 7:35 PM, Mitchell Zakocs wrote:
> > Checked through the shooter code blame and history and nothing has changed since Friday except for changing the button ID from 1 to 4.
> > On Friday, we tested it on Euans computer without using any sort of breakout USB box, the controllers were hooked up directly to his USB ports.
> > Here's what we should do to try and fix the issue:
> > 1. Make sure the shooter motor controller is hooked up to the right port on the RoboRIO
> Motors are not on ports on the RoboRIO, they are all on the CAN (Controller Area Network) Bus, each with a unique ID. These ID's are defined in The Contract, configured into the motor controllers (Phoenix Tuner; Lucky?), and are also defined in Constants.java for use in the program (RobotContainer.java). Constants.java and RobotContainer.java changed on Monday. Were the CAN ID's cross-checked between the H/W and S/W?
> >
> > 2. Make sure the two controllers are actually functioning properly, we can check this in driverstation
> 
> Never mind functioning properly, test to answer the questions "is this the driver's joystick?" and "is this the shooter joystick?" Revise in the driver station as required. Do not just swap USB ports. This must be part of the driver setup checklist.
> 
> We need to use USB port multipliers to reduce the wear and tear on the computers.
> >
> > 3. Try the controllers plugged directly into the USB ports and possibly recreate conditions w Euans computer on Friday
> 
> Nope. See (2).
> 
> We keep ignoring this: use SmartDashboard calls, LiveWindow calls and Test Mode to instrument the code and see what the robot is up to when it is not behaving as imagined, and for hardware testing.
> 
> What's different on Euan's computer?
> 
> .
> 
> .
> 
> .
> 
> Time's up. The intermediate files created in the build process in the workspace he is using. If he were to check out the same branch that is trouble elsewhere into a new workspace, that project would have the same problems.
> 
> Some of the problem seems to be that the merge between the "mitch" and "EuanB" branches did not result in what you wanted.
> >
> > 4. If all of this fails, we can try and test the shooter motor by just running it as soon as the robot turns on or through the CANSparkMax software to make sure the controller and motor are working properly
> See (3).
> >
> > I know that we don't want to have to use Euans laptop every time we want to use the shooter, but actually getting the motor to work again would make us not look like clowns in front of the harsh Charlie and Wendell and also help
> Too Late
> >  us figure out what's going on.
> > Thanks guys.
> >
>  See ya in Flag,
> 
>  Tim
> 

Thanks for your kind response Tim, with all due respect.

Wanted to comment on a couple things though:
1. Oops, I meant to say let's check the CAN ID's on the motor controllers and make sure that they're still the same with what's in our software. Like you said we need to make sure that the software and hardware match. I wrote this kinda late at night so it's probably my brain acting up.
2. I wasn't suggesting that we just swap USB ports meaninglessly and hope that it works, I was suggesting that we actually test the controllers with the input section of DriverStation and make sure that all the buttons are actually registering correctly. Figuring out which controller is which is extremely easy in that input screen on DriverStation since we know 0 is drive and 1 is shooter. I can show you tomorrow. If theres a way to actually label them in DriverStation or another way let's do that too, otherwise the method I just mentioned works perfectly fine.
3. I know it's a good idea to use SmartDashboard to monitor all our variables and stuff like that but frankly I have no clue how to do that. If you know how to do that then show us tomorrow or we can all figure it out together. Also, I don't know what's different on Euan's computer but since it worked on his on Friday it couldn't hurt to try. I don't mean to say that he should create a new project with the same code and deploy that to the robot, obviously that wouldn't do anything. It wasn't working on Lucky or Katies computer so it might be related to that, definitely not the first thing we should try though. Lastly, there is a chance that our merges didn't happen correctly. I thoroughly went through the git blame and history for RobotContainer, the shooter subsystem, constants and the shooter commands and found that our merges seemed to have happened fine, but I could have missed something small yet important. Like I said in the OP, I also didn't see any changes in the history or blame of those files that could have changed the behavior of our shooter system, so I'm almost certain it has nothing to do with this but we can check again together at the next meeting.
4. It probably would be a good idea to skip all that unnecessary troubleshooting with the CAN software and just try and get the DriverStation and LiveWindow stuff to work.
5. "Too Late," I appreciate you being so condescending and belittling to all of the programmers when we're working our asses off to get this code to work before this weekend.
6. I thankfully won't be in Flagstaff for the NAU competition, but I wish you and the programming team good luck.

Warmest Regards,
Mitch

**Comment by mzakocs** [comment]
But for real we need to come up with a plan of action for tomorrow so we don't waste the entire day, we need to get this fixed as soon as possible. Do you have any suggestions @tcjinaz

**Comment by tcjinaz** [comment]
Work out the sequence of OS commands that result in a particular remote Git branch being extracted into a local VSCode folder containing the local copy of the Git repo. Consider using the Git interface in VSCode instead of the command line tool. Confirm that the code builds, can be downloaded to the RoboRIO and executes without crashing.

Validate that the CAN addresses of peripherals match the addresses in Constants.java and RobotContainer.java

Create a new branch in the local Git repo.

Add LiveWindow code to enable individual motor testing from the driver's computer. https://docs.wpilib.org/en/latest/docs/software/wpilib-tools/smartdashboard/test-mode-and-live-window/displaying-LiveWindow-values.html#displaying-livewindow-values

Test each motor. If all can be controlled as we expect, commit the code, tag the commit, merge the branch with the local Master, push (with tags) to the Remote

Write a step by step procedure for the drivers to ensure each has the appropriate joystick in their hands. Test with the drivers, revise as required.

Commands can be used in Test Mode with LiveWindows. Add and test code to do so to each command. Be careful with the climber commands, with their dependencies on button presses and releases, and different starting states for the mechanisms, they could be difficult to test this way. Commit and tag locally after each successful test development. Push to remote repo, merge to Master on occasion. Some subsystem behaviors might be difficult to implement this way.

Create an Autonomous command that runs a command in autonomous that is selected by the driver. Look at the SelectCommand example. Make the default command drive forward the length of the robot, plus a smidge. The SelectCommand is new this year, I am not sure all of the hooks are in to make it usable like this. We may need to revert to using a SendableChooser through the SmartDashboard.

Add and test other autonomous behaviors. Check with the Drive and Scout teams on what might be useful.

**Comment by mzakocs** [comment]
> Work out the sequence of OS commands that result in a particular remote Git branch being extracted into a local VSCode folder containing the local copy of the Git repo. Consider using the Git interface in VSCode instead of the command line tool. Confirm that the code builds, can be downloaded to the RoboRIO and executes without crashing.
> 
> Validate that the CAN addresses of peripherals match the addresses in Constants.java and RobotContainer.java
> 
> Create a new branch in the local Git repo.
> 
> Add LiveWindow code to enable individual motor testing from the driver's computer. https://docs.wpilib.org/en/latest/docs/software/wpilib-tools/smartdashboard/test-mode-and-live-window/displaying-LiveWindow-values.html#displaying-livewindow-values
> 
> Test each motor. If all can be controlled as we expect, commit the code, tag the commit, merge the branch with the local Master, push (with tags) to the Remote
> 
> Write a step by step procedure for the drivers to ensure each has the appropriate joystick in their hands. Test with the drivers, revise as required.
> 
> Commands can be used in Test Mode with LiveWindows. Add and test code to do so to each command. Be careful with the climber commands, with their dependencies on button presses and releases, and different starting states for the mechanisms, they could be difficult to test this way. Commit and tag locally after each successful test development. Push to remote repo, merge to Master on occasion. Some subsystem behaviors might be difficult to implement this way.
> 
> Create an Autonomous command that runs a command in autonomous that is selected by the driver. Look at the SelectCommand example. Make the default command drive forward the length of the robot, plus a smidge. The SelectCommand is new this year, I am not sure all of the hooks are in to make it usable like this. We may need to revert to using a SendableChooser through the SmartDashboard.
> 
> Add and test other autonomous behaviors. Check with the Drive and Scout teams on what might be useful.

Perfect, this is a great checklist. Thank you Tim.
To everyone else lets try to get this stuff done as soon as possible, I'm hoping we don't hit too many snags and we can get all of this implemented by the end of Friday

**Comment by tcjinaz** [comment]
Move this thread to programmers@pridetronics.com please. Kill the github
connection.
Thanks, Tim

**Comment by mzakocs** [comment]
> Move this thread to programmers@pridetronics.com please. Kill the github connection. Thanks, Tim
> […](#)

Alright, there’s not much else to discuss. I’ll go ahead and close it.
