### ISSUE TITLE
ASCII Art

### ISSUE THREAD

**Issue by tcjinaz** [Pridetronics/InfiniteRechargeV3#4]
Please remove ASCII art from source https://github.com/Pridetronics/InfiniteRechargeV3/blob/master/src/main/java/frc/robot/RobotContainer.java

**Comment by euanblackstone** [comment]
While this ascii art kin hae distracted us fae oor code, althoogh I doubt th' validity o' this statement as thae murals wur dreamt o' by me while mah leisurely hours, I dae declare thae glorious picters shall be preservéd in mines mynd, yit nae in thine code; th' hert o' this issue is that thae murals kin represent a con, though I postulate thae represent a pro ower than a con, fur th' photie o' linus protecting oor code doth keep oor personality be kept in th' code; th' deletion o' linus fae th' software dae murdurr th' semblance o' character we hath injected intae th' code, yit it wull be removéd tae cull th' line count as if a quota oan they wha dae seek entry intae countries; th' logistics o' mines argument kin be cornered intae a single line, "the ascii art has been removed."
